export {Layout as PageLayout} from "./Layout"
export {Noticias as PageNoticias} from "./Noticias"
export {Login as PageLogin} from "./Login"
export {Write as PageWrite} from "./Write"
export {Noticia as PageNoticia} from "./Noticia"
export {ProgAz as ProgramaAz} from "./ProgramaAz"
export {EspOri as EsporteOri} from "./Orientacao"
export {Part as Participe} from "./Participe"