export {Header as ComponentHeader} from "./ComponentHeader"
export {Footer as ComponentFooter} from "./ComponentFooter"
export {saiba_mais as ComponentSaibaMais} from "./SaibaMais"
export {Noticia as Noticia} from "./Noticia"
export {Competicao as Competicao} from "./Competicao"